### PR TITLE
Fix format specifier for uint64_t

### PR DESCRIPTION
**Pull request by foonathan**
As discussed in #169.

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
Seems to be a problem with inttypes.h not being found on older MSVC versions :(

**Comment by foonathan** [comment]
Oh, I haven't looked at the CI results, added a workaround.

**Comment by foonathan** [comment]
I'm an idiot :D

**Comment by foonathan** [comment]
Okay, sorry about the commit spam, happens when you quickly write something while actually working on something else. :)

**Comment by MathieuDuponchelle** [comment]
the travis fail seems to be unrelated (timeout after 10 minutes), I'm not sure how to trigger a new run, @foonathan maybe if you push -f it will do the trick ?

**Comment by foonathan** [comment]
AFAIK the owner of the project has a restart button for each build.

**Comment by jgm** [comment]
Rebuilt and it's all green now.

+++ Jonathan Müller [Dec 23 16 23:22 ]:

**Comment by MathieuDuponchelle** [comment]
Looks good to me otherwise for what it's worth :)

**Comment by jgm** [comment]
Obsoleted by #174.

**Pull request closed without merging**
