### PR TITLE
Further optimize utf8proc_valid

### PR DESCRIPTION
**Pull request by nwellnhof**
Assume a multi-byte sequence and rework switch statement into if/else
for another 2% speedup.

### CODE REVIEW

**Comment by jgm** [comment]
After merging this, I ran my own benchmarks, and I see a slight slowdown (median from 0.250 to 0.255) rather than a speedup.  clang/OSX/64 bit.
I see no change on gcc/linux/32 bit.
I'm happy to keep this change, if you think the code is better.  But I didn't see a speed boost from it.

**Comment by nwellnhof** [comment]
I was testing with gcc 4.9.1, 32-bit Linux, Celeron G1840T @ 2.50GHz (Haswell). I also tested with benchinput.md copied 8 times over because I only get hundredths-of-seconds precision with `time -p`. My results: mean = 1.0750, median = 1.0700 vs mean = 1.1060, median = 1.100

**Comment by nwellnhof** [comment]
I also see a 2% slowdown on clang-602.0.53, OS X 10.10, 64-bit. Feel free to revert the commit.

**Comment by jgm** [comment]
I'll revert.

**Pull request merged**
