### PR TITLE
Fixed implicit casts from `size_t` to `int`.

### PR DESCRIPTION
**Pull request by neonichu**
Mostly by actually using `size_t`, except for the cases where negative values were considered valid, there I have stuck with `long`. The latter is of course all potential bugs, but at least they are more explicit now.

This makes it nicer to use cmark on iOS where `-Wshorten-64-to-32` is a default warning.

### CODE REVIEW

**Comment by jgm** [comment]
@nwellnhof, I'd be interested in your feedback on the proposed change.

@neonichu, this seems incomplete - note the warnings on the travis build:
https://travis-ci.org/jgm/cmark/builds/48927694

**Comment by neonichu** [comment]
@jgm oh, it indeed is. It appears I didn't have `-Wsign` set, will amend.

**Comment by nwellnhof** [comment]
I would prefer a patch that doesn't change the types of struct members or function parameters unless there's a really good reason. Using `size_t` for things like header levels just to fix some warnings isn't the right approach.

Instead, I'd propose to add explicit casts in the places where the warnings appear, and maybe add a `TODO` comment if the cast looks unsafe. Changing the types of local variables is OK.

**Comment by jgm** [comment]
+++ Nick Wellnhofer [Jan 30 15 13:43 ]:
>I would prefer a patch that doesn't change the types of struct members or function parameters unless there's a really good reason. Using `size_t` for things like header levels just to fix some warnings isn't the right approach.
>
>Instead, I'd propose to add explicit casts in the places where the warnings appear, and maybe add a `TODO` comment if the cast looks unsafe. Changing the types of local variables is OK.

This sounds like the right approach to me, too.

**Comment by nwellnhof** [comment]
This should be fixed now.

**Pull request closed without merging**
